x-common-config: &common-config
    restart: "no"
    networks:
      - freudbot-dev-network

services:
    freudbot-dev-nginx:
        <<: *common-config
        image: nginx:alpine
        container_name: freudbot-dev-nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./website/build/:/srv/www/freudbot
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./nginx/certs:/etc/nginx/certs
        depends_on:
          - freudbot-dev-website
          - freudbot-dev-api

    freudbot-dev-bot:
        <<: *common-config
        build:
            context: .
            dockerfile: Dockerfile.bot
        container_name: freudbot-dev-bot
        logging:
            options:
                max-size: "100m"
        environment:
          - DB_URL=postgresql+asyncpg://freudbot@freudbot-dev-database/freudbot
          - PGPASSWORD=freudbot

          - CH_URL=redis://@freudbot_cache:6379/0
        secrets:
          - discord_token
        depends_on:
          - freudbot-dev-database
          - freudbot-dev-cache
          - freudbot-dev-queue

    freudbot-dev-website:
        <<: *common-config
        build:
            context: ./website
            dockerfile: Dockerfile.dev
        container_name: freudbot-dev-website
        ports:
          - "3000:5173"
        environment:
          - PUBLIC_API_URL=https://freudbot.local/api
        volumes:
          - ./website:/freudbot-website
        depends_on:
            - freudbot-dev-api

    freudbot-dev-api:
        <<: *common-config
        build:
            context: ./api
        container_name: freudbot-dev-api
        logging:
            options:
                max-size: "100m"
        ports:
          - "4000:80"
          - "6669:6669"
        environment:
          - DB_URL=postgres://freudbot:freudbot@freudbot-dev-database/freudbot
          - CACHE_URL=redis://@freudbot-dev-cache:6379/0
          - AMQP_URL=amqp://freudbot-dev-queue:5672/%2f

          - REDIRECT_URL=https://freudbot.local/api/auth/callback
          - AUTH_URL=https://discord.com/api/oauth2/authorize?response_type=code
          - TOKEN_URL=https://discord.com/api/oauth2/token

          - BASE_URL=https://freudbot.local

          - COOKIE_DOMAIN=freudbot.local
          - PKCE_VERIFIER_COOKIE_NAME=freudbot_pkce_uuid
          - CSRF_TOKEN_COOKIE_NAME=freudbot_csrf
          - OAUTH_REDIRECT_COOKIE_NAME=freudbot_oauth_redirect
          - ACCESS_TOKEN_COOKIE_NAME=freudbot_discord_access_token
          - REFRESH_TOKEN_COOKIE_NAME=freudbot_discord_refresh_token

          - PKCE_VERIFIER_COOKIE_LIFESPAN=60
          - CSRF_TOKEN_COOKIE_LIFESPAN=60
          - OAUTH_REDIRECT_COOKIE_LIFESPAN=60
          - ACCESS_TOKEN_COOKIE_LIFESPAN=604800
          - REFRESH_TOKEN_COOKIE_LIFESPAN=1814400
        secrets:
          - discord_oauth_credentials
          - discord_token
          - gmail_smtp_credentials
        depends_on:
          - freudbot-dev-database
          - freudbot-dev-cache
          - freudbot-dev-queue

    freudbot-dev-database:
        <<: *common-config
        image: postgres:17-alpine
        container_name: freudbot-dev-database
        logging:
            options:
                max-size: "100m"
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=freudbot
          - POSTGRES_USER=freudbot
          - POSTGRES_DB=freudbot

    freudbot-dev-cache:
        <<: *common-config
        image: redis:7-alpine
        container_name: freudbot-dev-cache
        logging:
            options:
                max-size: "100m"
        ports:
          - "6379:6379"

    freudbot-dev-queue:
        <<: *common-config
        image: rabbitmq:4-alpine
        container_name: freudbot-dev-queue
        logging:
            options:
                max-size: "100m"
        ports:
          - "5672:5672"

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
    discord_oauth_credentials:
        file: ./secrets/discord_oauth_credentials.txt
    gmail_smtp_credentials:
        file: ./secrets/gmail_smtp_credentials.txt

networks:
    freudbot-dev-network:
        name: freudbot-dev-network
        driver: bridge
