services:
    freudbot:
        image: ghcr.io/tibo-ulens/freudbot:latest
        container_name: freudbot
        environment:
          - DB_URL=postgresql+asyncpg://postgres_user@freudbot_db/freudbot
          - PGPASSWORD=postgres_password

          - CH_URL=redis://@freudbot_cache:6379/0
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_token
        depends_on:
          - freudbot_db
          - freudbot_cache

    freudbot_api:
        image: ghcr.io/tibo-ulens/freudbot_api:latest
        container_name: freudbot_api
        ports:
          - "3000:80"
        environment:
          - BASE_URL=http://localhost:3000
          - HOMEPAGE_URL=http://localhost:5173
          - SESSION_COOKIE_DOMAIN=.localhost
          - ACCESS_COOKIE_NAME=DISCORD_ACCESS_TOKEN
          - REFRESH_COOKIE_NAME=DISCORD_REFRESH_TOKEN

          - DB_URL=postgresql+asyncpg://postgres_user@freudbot_db/freudbot
          - PGPASSWORD=postgres_password
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_oauth_credentials
          - discord_token
        healthcheck:
            test: curl --fail http://localhost/ || exit 1
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s
        depends_on:
          - freudbot

    freudbot_db:
        image: postgres:17-alpine
        container_name: freudbot_db
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USER=postgres_user
          - POSTGRES_DB=freudbot
        ports:
          - "5432:5432"
        volumes:
          - freudbot_data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -d freudbot -h freudbot_db -U postgres_user
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s

    freudbot_cache:
        image: redis:7-alpine
        container_name: freudbot_cache
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        ports:
          - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    freudbot_data:
        external: true

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
    discord_oauth_credentials:
        file: ./secrets/discord_oauth_credentials.txt
    gmail_smtp_credentials:
        file: ./secrets/gmail_smtp_credentials.txt
