version: '3'

services:
    freud_bot:
        image: ghcr.io/tibo-ulens/freud_bot:latest
        container_name: freud_bot
        environment:
          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_token
          - smtp_credentials
        depends_on:
          - freud_bot_db

    freud_bot_dev:
        build:
            context: .
            dockerfile: Dockerfile.bot
        container_name: freud_bot_dev
        restart: "no"
        environment:
          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_token
          - smtp_credentials
        depends_on:
          - freud_bot_db

    freud_bot_webconfig:
        image: ghcr.io/tibo-ulens/freud_bot_webconfig:latest
        container_name: freud_bot_webconfig
        ports:
          - "3000:80"
        environment:
          - BASE_URL=http://localhost:3000
          - SESSION_COOKIE_DOMAIN=.localhost
          - SESSION_COOKIE_NAME=freud_bot_webconfig_session

          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_oauth_credentials
          - discord_token
        depends_on:
          - freud_bot

    freud_bot_webconfig_dev:
        build:
            context: .
            dockerfile: Dockerfile.webconfig
        container_name: freud_bot_webconfig_dev
        restart: "no"
        ports:
          - "3000:80"
        environment:
          - BASE_URL=http://localhost:3000
          - SESSION_COOKIE_DOMAIN=.localhost
          - SESSION_COOKIE_NAME=freud_bot_webconfig_session

          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_oauth_credentials
          - discord_token
        depends_on:
          - freud_bot_dev

    freud_bot_db:
        image: postgres:alpine
        container_name: freud_bot_db
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USER=postgres_user
          - POSTGRES_DB=freud_bot
        ports:
          - "5432:5432"
        volumes:
          - freud_bot_data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -d freud_bot -h freud_bot_db -U postgres_user
            interval: 10m
            timeout: 5s
            retries: 2

volumes:
    freud_bot_data:
        external: true

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
    smtp_credentials:
        file: ./secrets/smtp_credentials.txt
    discord_oauth_credentials:
        file: ./secrets/discord_oauth_credentials.txt
