version: '3'

services:
    freud_bot:
        image: ghcr.io/tibo-ulens/freud_bot:latest
        container_name: freud_bot
        environment:
          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password

          - CACHE_HOST=freud_bot_cache
          - CACHE_PORT=6379

          - GUILD_ID=983088370509053983
          - VERIFY_CHANNEL=983088370966212609
          - VERIFIED_ROLE=Verified
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_token
          - smtp_credentials
        depends_on:
          - freud_bot_db
          - freud_bot_cache
    freud_bot_dev:
        build:
            context: .
        container_name: freud_bot_dev
        restart: "no"
        environment:
          - DB_URL=postgresql+asyncpg://postgres_user@freud_bot_db/freud_bot
          - PGPASSWORD=postgres_password

          - CACHE_HOST=freud_bot_cache
          - CACHE_PORT=6379

          - GUILD_ID=983088370509053983
          - VERIFY_CHANNEL=983088370966212609
          - VERIFIED_ROLE=Verified
        logging:
            options:
                max-size: "4096m"
        secrets:
          - discord_token
          - smtp_credentials
        depends_on:
          - freud_bot_db
          - freud_bot_cache

    freud_bot_db:
        image: postgres:alpine
        container_name: freud_bot_db
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        environment:
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_USER=postgres_user
          - POSTGRES_DB=freud_bot
        ports:
          - "5432:5432"
        volumes:
          - freud_bot_data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -d freud_bot -h freud_bot_db -U postgres_user
            interval: 10m
            timeout: 5s
            retries: 2

    freud_bot_cache:
        image: redis:latest
        container_name: freud_bot_cache
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        ports:
          - "6379:6379"

volumes:
    freud_bot_data:
        external: true

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
    smtp_credentials:
        file: ./secrets/smtp_credentials.txt
