[tool.poetry]
name = "freud_bot"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.0.1"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.40"}
alembic = "^1.8.1"
asyncpg = "^0.26.0"
selenium = "^4.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
