# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]

[migrations_directory]
dir = "/home/tibo/projects/bois/freud_bot/api/migrations"
