name: Release new version

on:
    push:
        tags:
          - "v*"

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: parse tag
            id: parse_tag
            run: "echo ${{ github.ref }} | sed 's#^refs/tags/v#::set-output name=version::#'"
          - name: create release
            id: create_release
            uses: release-drafter/release-drafter@v5
            with:
                name: v${{ steps.parse_tag.outputs.version }}
                tag: v${{ steps.parse_tag.outputs.version }}
                version: v${{ steps.parse_tag.outputs.version }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          - name: build new image
            run: docker build . -t ghcr.io/tibo-ulens/freud_bot:${{ steps.parse_tag.outputs.version }}
          - name: log in to ghcr
            run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          - name: tag new image as latest
            run: docker tag ghcr.io/tibo-ulens/freud_bot:${{ steps.parse_tag.outputs.version }} ghcr.io/tibo-ulens/freud_bot:latest
          - name: push the new image
            run: docker push --all-tags ghcr.io/tibo-ulens/freud_bot
